--DROP TABLE ROOM;
CREATE TABLE ROOM(
  ID NUMBER,
  CONSTRAINT ROOM_PK PRIMARY KEY(ID),
  NUMBER_OF_GUESTS NUMBER NOT NULL,
  PRICE FLOAT CHECK(PRICE >= 0),
  BREAKFAST_INCLUDED NUMBER(1,0) DEFAULT 0,
  PETS_ALLOWED NUMBER(1,0) DEFAULT 0,
  DATE_AVALIABLE_FROM TIMESTAMP NOT NULL,
  HOTEL_ID NUMBER,
  CONSTRAINT HOTEL_FK FOREIGN KEY(HOTEL_ID) REFERENCES HOTEL(ID)
);

--DROP SEQUENCE ROOM_PK_SEQ;
CREATE SEQUENCE ROOM_PK_SEQ START WITH 1 INCREMENT BY 1;