--DROP TABLE FP_HOTEL;
CREATE TABLE FP_HOTEL(
  ID NUMBER,
  CONSTRAINT FP_HOTEL_PK PRIMARY KEY(ID),
  HOTEL_NAME NVARCHAR2(50) NOT NULL,
  HOTEL_COUNTRY NVARCHAR2(50),
  HOTEL_CITY NVARCHAR2(50),
  HOTEL_STREET NVARCHAR2(50)
);

--DROP SEQUENCE FP_HOTEL_PK_SEQ;
CREATE SEQUENCE FP_HOTEL_PK_SEQ START WITH 1 INCREMENT BY 1;