CREATE TABLE FP_USER(
  ID NUMBER,
    CONSTRAINT FP_USER_PK PRIMARY KEY(ID),
  USER_NAME NVARCHAR2(100) NOT NULL,
  PASSWORD NVARCHAR2(50) NOT NULL,
  COUNTRY NVARCHAR2(50),
  USER_TYPE_ID NUMBER,
    CONSTRAINT FP_USER_TYPE_FK FOREIGN KEY(USER_TYPE_ID) REFERENCES FP_USER_TYPE(ID)
);

CREATE SEQUENCE FP_USER_PK_SEQ START WITH 1 INCREMENT BY 1;
