CREATE TABLE FP_ORDER(
  ID NUMBER,
    CONSTRAINT FP_ORDER_PK PRIMARY KEY(ID),
  USER_ID NUMBER,
    CONSTRAINT FP_USER_FK FOREIGN KEY(USER_ID) REFERENCES FP_USER(ID),
  ROOM_ID NUMBER,
    CONSTRAINT FP_ROOM_FK FOREIGN KEY(ROOM_ID) REFERENCES FP_ROOM(ID),
  DATE_FROM TIMESTAMP NOT NULL,
  DATE_TO TIMESTAMP NOT NULL,
  MONEY_PAID FLOAT CHECK(MONEY_PAID > 0)
);

CREATE SEQUENCE FP_ORDER_PK_SEQ START WITH 1 INCREMENT BY 1;